# <center>MobileNet - Pytorch

# Step 1: Prepare data

In [1]:
# MobileNet-Pytorch
import argparse 
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR
from torchvision import datasets, transforms
from torch.autograd import Variable
from torch.utils.data.sampler import SubsetRandomSampler
from sklearn.metrics import accuracy_score
#from mobilenets import mobilenet

use_cuda = torch.cuda.is_available()
use_cudause_cud  = torch.cuda.is_available()
dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor

In [2]:
# Train, Validate, Test. Heavily inspired by Kevinzakka https://github.com/kevinzakka/DenseNet/blob/master/data_loader.py

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

valid_size=0.1

# define transforms
valid_transform = transforms.Compose([
        transforms.ToTensor(),
        normalize
])

train_transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    normalize
])


# load the dataset
train_dataset = datasets.CIFAR10(root="data", train=True, 
            download=True, transform=train_transform)

valid_dataset = datasets.CIFAR10(root="data", train=True, 
            download=True, transform=valid_transform)

num_train = len(train_dataset)
indices = list(range(num_train))
split = int(np.floor(valid_size * num_train)) #5w张图片的10%用来当做验证集


np.random.seed(42)
np.random.shuffle(indices) # 随机乱序[0,1,...,49999]

train_idx, valid_idx = indices[split:], indices[:split]


train_sampler = SubsetRandomSampler(train_idx) # 这个很有意思
valid_sampler = SubsetRandomSampler(valid_idx)


# ------------------------- 使用不同的批次大小 ------------------------------------
show_step=10  # 批次大，show_step就小点
max_epoch=60  # 训练最大epoch数目
train_loader = torch.utils.data.DataLoader(train_dataset, 
                batch_size=1024, sampler=train_sampler)

valid_loader = torch.utils.data.DataLoader(valid_dataset, 
                batch_size=1024, sampler=valid_sampler)


test_transform = transforms.Compose([
    transforms.ToTensor(), normalize
])

test_dataset = datasets.CIFAR10(root="data", 
                                train=False, 
                                download=True,transform=test_transform)

test_loader = torch.utils.data.DataLoader(test_dataset, 
                                          batch_size=64, 
                                          shuffle=True)

Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified


# Step 2: Model Config

In [3]:
# 32  缩放5次到 1x1@1024 
# From https://github.com/kuangliu/pytorch-cifar 
import torch
import torch.nn as nn
import torch.nn.functional as F


class Block(nn.Module):
    '''Depthwise conv + Pointwise conv'''
    def __init__(self, in_planes, out_planes, stride=1):
        super(Block, self).__init__()
        
        # 分组卷积数=输入通道数
        self.conv1 = nn.Conv2d(in_planes, in_planes, kernel_size=3, stride=stride, padding=1, groups=in_planes, bias=False)
        
        self.bn1 = nn.BatchNorm2d(in_planes)
        
        self.conv2 = nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=1, padding=0, bias=False)
        
        self.bn2 = nn.BatchNorm2d(out_planes)

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = F.relu(self.bn2(self.conv2(out)))
        return out


class MobileNet(nn.Module):
    # (128,2) means conv planes=128, conv stride=2, by default conv stride=1
    cfg = [64, (128,2), 128, (256,2), 256, (512,2), 512, 512, 512, 512, 512, (1024,2), 1024]

    def __init__(self, num_classes=10):
        super(MobileNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1, bias=False)
        
        self.bn1 = nn.BatchNorm2d(32)
        self.layers = self._make_layers(in_planes=32) # 自动化构建层
        one_conv_kernel_size=103
        self.linear = nn.Conv1d(1, 1, one_conv_kernel_size, stride=103,padding=3,groups=1,dilation=1,bias=True) # nn.Linear(1024, num_classes)

    def _make_layers(self, in_planes):
        layers = []
        for x in self.cfg:
            out_planes = x if isinstance(x, int) else x[0]
            stride = 1 if isinstance(x, int) else x[1]
            layers.append(Block(in_planes, out_planes, stride))
            in_planes = out_planes
        return nn.Sequential(*layers)

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.layers(out)
        out = F.avg_pool2d(out, 2)
        out = out.view(out.size(0), -1)
        #print("size1:",out.shape)
        bs=out.shape[0]
        out=out.view(bs,1,1024)
        out = self.linear(out)
        #print("size1:",out.shape)
        out=out.view(bs,10) # 10 class
        return out

In [4]:
# From https://github.com/Z0m6ie/CIFAR-10_PyTorch
#model = mobilenet(num_classes=10, large_img=False)

# From https://github.com/kuangliu/pytorch-cifar 
if torch.cuda.is_available():
    model=MobileNet(10).cuda()
else:
    model=MobileNet(10)

optimizer = optim.Adam(model.parameters(), lr=0.01)
scheduler = StepLR(optimizer, step_size=10, gamma=0.5)
criterion = nn.CrossEntropyLoss()

In [5]:
# Implement validation
def train(epoch):
    model.train()
    #writer = SummaryWriter()
    for batch_idx, (data, target) in enumerate(train_loader):
        if use_cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data), Variable(target)
        optimizer.zero_grad()
        output = model(data)
        correct = 0
        pred = output.data.max(1, keepdim=True)[1] # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).sum()
        
        loss = criterion(output, target)
        loss.backward()
        accuracy = 100. * (correct.cpu().numpy()/ len(output))
        optimizer.step()
        if batch_idx % show_step == 0:
            if batch_idx % 4*show_step==0:
                print(torch.abs(model.layers[12].conv2.weight).sum())
                print(model.layers[12].conv2.weight.shape)
                print(model.layers[12].conv2.weight)
                
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}, Accuracy: {:.2f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item(), accuracy))
            #writer.add_scalar('Loss/Loss', loss.item(), epoch)
            #writer.add_scalar('Accuracy/Accuracy', accuracy, epoch)
    scheduler.step()

In [6]:
def validate(epoch):
    model.eval()
    #writer = SummaryWriter()
    valid_loss = 0
    correct = 0
    for data, target in valid_loader:
        if use_cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data), Variable(target)
        output = model(data)
        valid_loss += F.cross_entropy(output, target, size_average=False).item() # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1] # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).sum()

    valid_loss /= len(valid_idx)
    accuracy = 100. * correct.cpu().numpy() / len(valid_idx)
    print('\nValidation set: Average loss: {:.4f}, Accuracy: {}/{} ({:.2f}%)\n'.format(
        valid_loss, correct, len(valid_idx),
        100. * correct / len(valid_idx)))
    #writer.add_scalar('Loss/Validation_Loss', valid_loss, epoch)
    #writer.add_scalar('Accuracy/Validation_Accuracy', accuracy, epoch)
    return valid_loss, accuracy

In [7]:
# Fix best model

def test(epoch):
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        if use_cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data), Variable(target)
        output = model(data)
        test_loss += F.cross_entropy(output, target, size_average=False).item() # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1] # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()

    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.2f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct.cpu().numpy() / len(test_loader.dataset)))

In [8]:
def save_best(loss, accuracy, best_loss, best_acc):
    if best_loss == None:
        best_loss = loss
        best_acc = accuracy
        file = 'saved_models/best_save_model.p'
        torch.save(model.state_dict(), file)
        
    elif loss < best_loss and accuracy > best_acc:
        best_loss = loss
        best_acc = accuracy
        file = 'saved_models/best_save_model.p'
        torch.save(model.state_dict(), file)
    return best_loss, best_acc

In [9]:
# Fantastic logger for tensorboard and pytorch, 
# run tensorboard by opening a new terminal and run "tensorboard --logdir runs"
# open tensorboard at http://localhost:6006/
from tensorboardX import SummaryWriter
best_loss = None
best_acc = None

import time 
SINCE=time.time()

for epoch in range(max_epoch):
    train(epoch)
    loss, accuracy = validate(epoch)
    best_loss, best_acc = save_best(loss, accuracy, best_loss, best_acc)
    
    NOW=time.time() 
    DURINGS=NOW-SINCE
    SINCE=NOW
    print("the time of this epoch:[{} s]".format(DURINGS))
    
#writer = SummaryWriter()
#writer.export_scalars_to_json("./all_scalars.json")

#writer.close()

#---------------------------- Test ------------------------------
test(epoch)

tensor(17876.0449, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 1.6158e-02]],

         [[-1.5721e-02]],

         [[ 5.0717e-03]],

         ...,

         [[ 3.0422e-02]],

         [[-1.4717e-02]],

         [[-1.7136e-02]]],


        [[[ 1.0009e-02]],

         [[-1.3958e-02]],

         [[ 1.9527e-02]],

         ...,

         [[-1.0740e-02]],

         [[ 5.4821e-03]],

         [[ 4.0501e-02]]],


        [[[-1.9136e-02]],

         [[-1.3957e-02]],

         [[-9.2750e-03]],

         ...,

         [[ 2.5767e-02]],

         [[-1.8304e-02]],

         [[-1.3609e-03]]],


        ...,


        [[[-7.8839e-03]],

         [[-1.4723e-02]],

         [[ 5.7652e-03]],

         ...,

         [[ 9.9766e-03]],

         [[ 2.6063e-02]],

         [[-2.1302e-02]]],


        [[[-3.5930e-02]],

         [[ 2.0733e-02]],

         [[ 3.8523e-03]],

         ...,

         [[ 3.3510e-03]],

         [[-1.1828e-02]],

         [[-1.5236e-02]]],


 

Train Epoch: 2 [10240/50000 (23%)]	Loss: 1.210823, Accuracy: 55.18
tensor(61245.9102, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 7.8230e-03]],

         [[-6.7339e-02]],

         [[ 7.1538e-02]],

         ...,

         [[-9.5010e-03]],

         [[ 4.8931e-02]],

         [[-1.9042e-02]]],


        [[[-1.3972e-01]],

         [[-9.0390e-02]],

         [[ 7.1027e-02]],

         ...,

         [[ 7.7392e-03]],

         [[ 7.1116e-02]],

         [[ 8.9553e-02]]],


        [[[-8.0375e-03]],

         [[ 4.2714e-02]],

         [[ 8.4415e-02]],

         ...,

         [[-2.2290e-02]],

         [[ 3.3986e-02]],

         [[ 2.2265e-02]]],


        ...,


        [[[ 3.7263e-02]],

         [[ 2.9946e-02]],

         [[ 6.0866e-02]],

         ...,

         [[-2.7122e-02]],

         [[ 5.9388e-02]],

         [[-9.7219e-02]]],


        [[[-1.6139e-01]],

         [[-2.7620e-02]],

         [[-1.4653e-02]],

         ...,

         [[-3.359

Train Epoch: 4 [30720/50000 (68%)]	Loss: 0.842954, Accuracy: 69.82
tensor(67879.8281, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 2.5952e-02]],

         [[-7.5499e-02]],

         [[ 6.1527e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 4.8477e-02]],

         [[-4.1075e-02]]],


        [[[-1.3588e-01]],

         [[-7.6239e-02]],

         [[ 1.7086e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 7.3945e-02]],

         [[ 7.9590e-02]]],


        [[[ 2.2563e-02]],

         [[ 3.6833e-02]],

         [[ 6.6583e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.1815e-02]],

         [[-1.0960e-02]]],


        ...,


        [[[ 3.9127e-02]],

         [[ 3.0121e-02]],

         [[ 5.8027e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 6.6757e-02]],

         [[-9.9915e-02]]],


        [[[-1.3185e-01]],

         [[-4.6767e-02]],

         [[-2.8793e-03]],

         ...,

         [[-2.850


Validation set: Average loss: 0.9740, Accuracy: 3431/5000 (68.00%)

the time of this epoch:[18.528116941452026 s]
tensor(72697., device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 2.5289e-02]],

         [[-7.8052e-02]],

         [[ 1.0648e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 4.6139e-02]],

         [[-4.6752e-02]]],


        [[[-1.4218e-01]],

         [[-8.3051e-02]],

         [[-2.4845e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 7.5472e-02]],

         [[ 6.8449e-02]]],


        [[[ 2.5620e-02]],

         [[ 3.1147e-02]],

         [[ 1.1773e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.1106e-02]],

         [[-2.6148e-02]]],


        ...,


        [[[ 3.8799e-02]],

         [[ 2.7117e-02]],

         [[ 3.9643e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 6.0935e-02]],

         [[-1.0239e-01]]],


        [[[-6.4372e-02]],

         [[-5.6041e-02]],

         [[-4.0

Train Epoch: 9 [10240/50000 (23%)]	Loss: 0.519471, Accuracy: 83.59
tensor(77331.2188, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 3.4587e-02]],

         [[-6.8436e-02]],

         [[ 2.3673e-03]],

         ...,

         [[-9.2328e-03]],

         [[ 5.1155e-02]],

         [[-2.2094e-02]]],


        [[[-1.4485e-01]],

         [[-7.4350e-02]],

         [[-4.2985e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 8.3429e-02]],

         [[ 7.6166e-02]]],


        [[[ 4.1700e-02]],

         [[ 4.6058e-02]],

         [[-2.8633e-03]],

         ...,

         [[-2.1528e-02]],

         [[ 3.1788e-02]],

         [[ 3.2468e-03]]],


        ...,


        [[[ 3.0493e-02]],

         [[ 2.1791e-02]],

         [[ 4.4946e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 6.0241e-02]],

         [[-9.5417e-02]]],


        [[[-9.6155e-03]],

         [[-7.2936e-02]],

         [[-5.2978e-02]],

         ...,

         [[-2.850

Train Epoch: 11 [30720/50000 (68%)]	Loss: 0.413900, Accuracy: 86.04
tensor(80595.5859, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 3.1812e-02]],

         [[-7.5195e-02]],

         [[ 2.8281e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 5.8508e-02]],

         [[-1.5440e-02]]],


        [[[-1.4784e-01]],

         [[-1.0064e-01]],

         [[-3.1201e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.5553e-02]],

         [[ 7.5943e-02]]],


        [[[ 3.9577e-02]],

         [[ 3.5388e-02]],

         [[ 2.5529e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.5150e-02]],

         [[ 7.8125e-03]]],


        ...,


        [[[ 2.7965e-02]],

         [[ 2.2367e-02]],

         [[ 2.5925e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.9083e-02]],

         [[-9.2485e-02]]],


        [[[-1.4568e-02]],

         [[-7.4995e-02]],

         [[-6.0596e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.4845, Accuracy: 4165/5000 (83.00%)

the time of this epoch:[18.455798387527466 s]
tensor(81404.2891, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.1341e-02]],

         [[-7.4354e-02]],

         [[ 2.8541e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 5.7204e-02]],

         [[-1.8071e-03]]],


        [[[-1.3726e-01]],

         [[-1.0046e-01]],

         [[-3.1978e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.5743e-02]],

         [[ 8.1043e-02]]],


        [[[ 5.0072e-02]],

         [[ 3.9209e-02]],

         [[ 2.6048e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.4438e-02]],

         [[ 2.1415e-02]]],


        ...,


        [[[ 2.2070e-02]],

         [[ 1.9652e-02]],

         [[ 2.6517e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 6.2125e-02]],

         [[-9.9784e-02]]],


        [[[ 3.9018e-04]],

         [[-7.6649e-02]],

         [[

Train Epoch: 16 [10240/50000 (23%)]	Loss: 0.270551, Accuracy: 90.53
tensor(82389.1875, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.2001e-02]],

         [[-7.3017e-02]],

         [[ 3.8340e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 5.6834e-02]],

         [[ 1.2520e-02]]],


        [[[-1.4305e-01]],

         [[-8.7056e-02]],

         [[-5.2767e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.0253e-02]],

         [[ 9.1488e-02]]],


        [[[ 5.1958e-02]],

         [[ 4.1339e-02]],

         [[ 3.0530e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.4008e-02]],

         [[ 3.9659e-02]]],


        ...,


        [[[ 2.1703e-02]],

         [[ 1.9665e-02]],

         [[ 2.0688e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.6505e-02]],

         [[-9.1607e-02]]],


        [[[-3.3134e-03]],

         [[-7.6141e-02]],

         [[-6.5067e-02]],

         ...,

         [[-2.85

Train Epoch: 18 [30720/50000 (68%)]	Loss: 0.316468, Accuracy: 88.77
tensor(83611.5625, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.6421e-02]],

         [[-7.3262e-02]],

         [[ 3.5326e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 5.7700e-02]],

         [[ 3.2278e-02]]],


        [[[-1.4258e-01]],

         [[-9.5477e-02]],

         [[-6.7574e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.0822e-02]],

         [[ 9.6192e-02]]],


        [[[ 5.7432e-02]],

         [[ 3.7913e-02]],

         [[ 2.7841e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.4503e-02]],

         [[ 5.7471e-02]]],


        ...,


        [[[ 1.7209e-02]],

         [[ 1.9180e-02]],

         [[ 1.3922e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.3900e-02]],

         [[-6.8698e-02]]],


        [[[ 7.4490e-03]],

         [[-8.0232e-02]],

         [[-5.8544e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.5174, Accuracy: 4172/5000 (83.00%)

the time of this epoch:[18.504482984542847 s]
tensor(84595.5469, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 3.9425e-02]],

         [[-6.4117e-02]],

         [[ 6.1736e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 5.7982e-02]],

         [[ 3.6203e-02]]],


        [[[-1.4873e-01]],

         [[-8.1081e-02]],

         [[-5.1739e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.1355e-02]],

         [[ 1.0024e-01]]],


        [[[ 5.0482e-02]],

         [[ 4.8508e-02]],

         [[ 5.5001e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.4839e-02]],

         [[ 6.1533e-02]]],


        ...,


        [[[ 2.0305e-02]],

         [[ 1.9047e-02]],

         [[ 2.4329e-03]],

         ...,

         [[-2.5991e-02]],

         [[ 5.2466e-02]],

         [[-6.5367e-02]]],


        [[[ 7.4652e-03]],

         [[-7.6956e-02]],

         [[

Train Epoch: 23 [10240/50000 (23%)]	Loss: 0.217995, Accuracy: 92.29
tensor(84850.7891, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 3.9277e-02]],

         [[-6.4791e-02]],

         [[ 6.7527e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.0327e-02]],

         [[ 4.8020e-02]]],


        [[[-1.4020e-01]],

         [[-7.9444e-02]],

         [[-4.0443e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.2298e-02]],

         [[ 1.0342e-01]]],


        [[[ 5.0600e-02]],

         [[ 4.8137e-02]],

         [[ 6.0634e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.5719e-02]],

         [[ 7.2785e-02]]],


        ...,


        [[[ 1.5989e-02]],

         [[ 1.9158e-02]],

         [[ 5.4087e-03]],

         ...,

         [[-2.5991e-02]],

         [[ 5.0460e-02]],

         [[-6.7462e-02]]],


        [[[ 3.1137e-02]],

         [[-7.8337e-02]],

         [[-7.3546e-02]],

         ...,

         [[-2.85

Train Epoch: 25 [30720/50000 (68%)]	Loss: 0.240643, Accuracy: 91.99
tensor(85199.3672, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.0013e-02]],

         [[-6.5732e-02]],

         [[ 7.4640e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.4467e-02]],

         [[ 5.6602e-02]]],


        [[[-1.3660e-01]],

         [[-8.8861e-02]],

         [[-3.4410e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.8321e-02]],

         [[ 1.0754e-01]]],


        [[[ 5.1940e-02]],

         [[ 4.7183e-02]],

         [[ 6.8019e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.7407e-02]],

         [[ 8.1070e-02]]],


        ...,


        [[[ 1.7436e-02]],

         [[ 1.9443e-02]],

         [[ 1.1046e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.0911e-02]],

         [[-7.6983e-02]]],


        [[[ 5.2587e-02]],

         [[-8.2321e-02]],

         [[-6.9884e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.4565, Accuracy: 4318/5000 (86.00%)

the time of this epoch:[18.495240449905396 s]
tensor(85505.6250, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.3054e-02]],

         [[-6.4583e-02]],

         [[ 6.9470e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.3034e-02]],

         [[ 4.9869e-02]]],


        [[[-1.3407e-01]],

         [[-8.6501e-02]],

         [[-4.0701e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.6741e-02]],

         [[ 1.0262e-01]]],


        [[[ 5.5624e-02]],

         [[ 4.8568e-02]],

         [[ 6.2712e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.6883e-02]],

         [[ 7.5305e-02]]],


        ...,


        [[[ 1.4993e-02]],

         [[ 1.8880e-02]],

         [[ 3.1403e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.5894e-02]],

         [[-8.1639e-02]]],


        [[[ 3.9565e-02]],

         [[-7.5190e-02]],

         [[

Train Epoch: 30 [10240/50000 (23%)]	Loss: 0.175318, Accuracy: 93.85
tensor(85909.4375, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.0516e-02]],

         [[-6.1308e-02]],

         [[ 7.2105e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.3700e-02]],

         [[ 5.2259e-02]]],


        [[[-1.3751e-01]],

         [[-8.4494e-02]],

         [[-3.4561e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.6669e-02]],

         [[ 1.0322e-01]]],


        [[[ 5.3015e-02]],

         [[ 5.1618e-02]],

         [[ 6.5969e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.7226e-02]],

         [[ 7.6859e-02]]],


        ...,


        [[[ 1.1758e-02]],

         [[ 1.9840e-02]],

         [[ 7.3206e-03]],

         ...,

         [[-2.5991e-02]],

         [[ 5.1830e-02]],

         [[-6.7534e-02]]],


        [[[ 4.6721e-02]],

         [[-8.1639e-02]],

         [[-6.2160e-02]],

         ...,

         [[-2.85

Train Epoch: 32 [30720/50000 (68%)]	Loss: 0.108408, Accuracy: 96.39
tensor(86044.2188, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.3183e-02]],

         [[-6.5486e-02]],

         [[ 7.0572e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.5150e-02]],

         [[ 5.9621e-02]]],


        [[[-1.3413e-01]],

         [[-9.2097e-02]],

         [[-3.4295e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.7711e-02]],

         [[ 1.0988e-01]]],


        [[[ 5.5720e-02]],

         [[ 4.5570e-02]],

         [[ 6.4533e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.7824e-02]],

         [[ 8.3921e-02]]],


        ...,


        [[[ 1.1987e-02]],

         [[ 1.8591e-02]],

         [[ 2.9411e-03]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4081e-02]],

         [[-6.7788e-02]]],


        [[[ 4.5107e-02]],

         [[-8.1691e-02]],

         [[-7.1060e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.4618, Accuracy: 4405/5000 (88.00%)

the time of this epoch:[18.494471788406372 s]
tensor(86108.3438, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.2867e-02]],

         [[-6.4074e-02]],

         [[ 7.4988e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.5986e-02]],

         [[ 6.0192e-02]]],


        [[[-1.3036e-01]],

         [[-9.2902e-02]],

         [[-2.5537e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.8947e-02]],

         [[ 1.0878e-01]]],


        [[[ 5.5324e-02]],

         [[ 4.6850e-02]],

         [[ 6.9308e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.8235e-02]],

         [[ 8.4107e-02]]],


        ...,


        [[[ 8.4661e-03]],

         [[ 1.7844e-02]],

         [[ 3.7420e-03]],

         ...,

         [[-2.5991e-02]],

         [[ 5.3818e-02]],

         [[-7.1648e-02]]],


        [[[ 6.1209e-02]],

         [[-8.3234e-02]],

         [[

Train Epoch: 37 [10240/50000 (23%)]	Loss: 0.111469, Accuracy: 96.58
tensor(86184.0938, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.6180e-02]],

         [[-6.5863e-02]],

         [[ 7.2321e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.4535e-02]],

         [[ 6.0067e-02]]],


        [[[-1.2654e-01]],

         [[-9.5934e-02]],

         [[-2.8146e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 9.7170e-02]],

         [[ 1.0763e-01]]],


        [[[ 5.8869e-02]],

         [[ 4.4721e-02]],

         [[ 6.6502e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.7585e-02]],

         [[ 8.4186e-02]]],


        ...,


        [[[ 8.3922e-03]],

         [[ 1.7902e-02]],

         [[ 1.0276e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4281e-02]],

         [[-7.5139e-02]]],


        [[[ 6.3605e-02]],

         [[-8.1151e-02]],

         [[-7.1413e-02]],

         ...,

         [[-2.85

Train Epoch: 39 [30720/50000 (68%)]	Loss: 0.098184, Accuracy: 96.78
tensor(86276.5938, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5669e-02]],

         [[-6.6643e-02]],

         [[ 7.2101e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.6522e-02]],

         [[ 6.5595e-02]]],


        [[[-1.2715e-01]],

         [[-1.0027e-01]],

         [[-2.9755e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0068e-01]],

         [[ 1.1270e-01]]],


        [[[ 5.8528e-02]],

         [[ 4.4040e-02]],

         [[ 6.6194e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.8423e-02]],

         [[ 8.9950e-02]]],


        ...,


        [[[ 1.1051e-02]],

         [[ 1.7444e-02]],

         [[ 1.3665e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.6094e-02]],

         [[-7.2181e-02]]],


        [[[ 7.1607e-02]],

         [[-8.1457e-02]],

         [[-6.9643e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.4684, Accuracy: 4449/5000 (88.00%)

the time of this epoch:[18.50426411628723 s]
tensor(86328.1250, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5314e-02]],

         [[-6.7072e-02]],

         [[ 7.2124e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.7216e-02]],

         [[ 6.7169e-02]]],


        [[[-1.2697e-01]],

         [[-1.0318e-01]],

         [[-2.9753e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0180e-01]],

         [[ 1.1581e-01]]],


        [[[ 5.8103e-02]],

         [[ 4.2962e-02]],

         [[ 6.6318e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.8763e-02]],

         [[ 9.1351e-02]]],


        ...,


        [[[ 1.0175e-02]],

         [[ 1.7625e-02]],

         [[ 1.0347e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.6642e-02]],

         [[-7.3054e-02]]],


        [[[ 6.6632e-02]],

         [[-8.1345e-02]],

         [[-

Train Epoch: 44 [10240/50000 (23%)]	Loss: 0.047668, Accuracy: 98.54
tensor(86359.4453, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5927e-02]],

         [[-6.7758e-02]],

         [[ 7.2595e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.8246e-02]],

         [[ 6.9252e-02]]],


        [[[-1.2594e-01]],

         [[-1.0429e-01]],

         [[-2.7949e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0328e-01]],

         [[ 1.1836e-01]]],


        [[[ 5.8806e-02]],

         [[ 4.1945e-02]],

         [[ 6.6858e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9237e-02]],

         [[ 9.3417e-02]]],


        ...,


        [[[ 1.1497e-02]],

         [[ 1.7976e-02]],

         [[ 1.3368e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4836e-02]],

         [[-7.7224e-02]]],


        [[[ 6.8321e-02]],

         [[-8.3447e-02]],

         [[-6.6708e-02]],

         ...,

         [[-2.85

Train Epoch: 46 [30720/50000 (68%)]	Loss: 0.060625, Accuracy: 97.56
tensor(86376.4297, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.4797e-02]],

         [[-6.6763e-02]],

         [[ 7.5005e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.8823e-02]],

         [[ 7.1067e-02]]],


        [[[-1.2784e-01]],

         [[-1.0172e-01]],

         [[-2.3525e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0419e-01]],

         [[ 1.2092e-01]]],


        [[[ 5.7604e-02]],

         [[ 4.3097e-02]],

         [[ 6.9422e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9512e-02]],

         [[ 9.5183e-02]]],


        ...,


        [[[ 8.1036e-03]],

         [[ 1.7634e-02]],

         [[ 1.0682e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4723e-02]],

         [[-7.8418e-02]]],


        [[[ 7.1868e-02]],

         [[-8.2045e-02]],

         [[-6.8969e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.5222, Accuracy: 4444/5000 (88.00%)

the time of this epoch:[18.535001039505005 s]
tensor(86403.4453, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5810e-02]],

         [[-6.7749e-02]],

         [[ 7.5332e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.8850e-02]],

         [[ 7.1542e-02]]],


        [[[-1.2431e-01]],

         [[-1.0502e-01]],

         [[-2.2053e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0344e-01]],

         [[ 1.2161e-01]]],


        [[[ 5.8738e-02]],

         [[ 4.1746e-02]],

         [[ 6.9766e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9529e-02]],

         [[ 9.5681e-02]]],


        ...,


        [[[ 9.0627e-03]],

         [[ 1.7444e-02]],

         [[ 1.0545e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4923e-02]],

         [[-7.6769e-02]]],


        [[[ 7.1898e-02]],

         [[-8.3406e-02]],

         [[

Train Epoch: 51 [10240/50000 (23%)]	Loss: 0.054295, Accuracy: 98.05
tensor(86412.2578, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5234e-02]],

         [[-6.8578e-02]],

         [[ 7.5821e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.7999e-02]],

         [[ 7.0954e-02]]],


        [[[-1.2311e-01]],

         [[-1.0813e-01]],

         [[-2.0119e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0127e-01]],

         [[ 1.2047e-01]]],


        [[[ 5.8077e-02]],

         [[ 4.0513e-02]],

         [[ 7.0317e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9156e-02]],

         [[ 9.5047e-02]]],


        ...,


        [[[ 1.1614e-02]],

         [[ 1.6842e-02]],

         [[ 1.4574e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.5338e-02]],

         [[-8.2618e-02]]],


        [[[ 6.8435e-02]],

         [[-8.2411e-02]],

         [[-6.9444e-02]],

         ...,

         [[-2.85

Train Epoch: 53 [30720/50000 (68%)]	Loss: 0.034038, Accuracy: 98.83
tensor(86419.6016, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.6227e-02]],

         [[-6.8336e-02]],

         [[ 7.7252e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.9086e-02]],

         [[ 7.1151e-02]]],


        [[[-1.2228e-01]],

         [[-1.0745e-01]],

         [[-1.8069e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0341e-01]],

         [[ 1.2049e-01]]],


        [[[ 5.9240e-02]],

         [[ 4.1033e-02]],

         [[ 7.1796e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9638e-02]],

         [[ 9.5334e-02]]],


        ...,


        [[[ 1.2259e-02]],

         [[ 1.6637e-02]],

         [[ 1.2357e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4962e-02]],

         [[-8.2021e-02]]],


        [[[ 6.7503e-02]],

         [[-8.2505e-02]],

         [[-6.8424e-02]],

         ...,

         [[-2.85


Validation set: Average loss: 0.5520, Accuracy: 4444/5000 (88.00%)

the time of this epoch:[18.469688415527344 s]
tensor(86418.7812, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5373e-02]],

         [[-6.9156e-02]],

         [[ 7.7111e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.9273e-02]],

         [[ 7.0454e-02]]],


        [[[-1.2328e-01]],

         [[-1.0936e-01]],

         [[-1.7608e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0369e-01]],

         [[ 1.1942e-01]]],


        [[[ 5.8264e-02]],

         [[ 3.9670e-02]],

         [[ 7.1719e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9753e-02]],

         [[ 9.4499e-02]]],


        ...,


        [[[ 1.2927e-02]],

         [[ 1.6932e-02]],

         [[ 1.0546e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.4231e-02]],

         [[-7.9561e-02]]],


        [[[ 6.8184e-02]],

         [[-8.3867e-02]],

         [[

Train Epoch: 58 [10240/50000 (23%)]	Loss: 0.028189, Accuracy: 99.12
tensor(86407.1016, device='cuda:0')
torch.Size([1024, 1024, 1, 1])
Parameter containing:
tensor([[[[ 4.5254e-02]],

         [[-6.8466e-02]],

         [[ 7.4596e-02]],

         ...,

         [[-9.2328e-03]],

         [[ 6.8923e-02]],

         [[ 7.0814e-02]]],


        [[[-1.2376e-01]],

         [[-1.0788e-01]],

         [[-2.1261e-02]],

         ...,

         [[ 6.7863e-03]],

         [[ 1.0276e-01]],

         [[ 1.2009e-01]]],


        [[[ 5.8148e-02]],

         [[ 4.0498e-02]],

         [[ 6.9092e-02]],

         ...,

         [[-2.1528e-02]],

         [[ 3.9595e-02]],

         [[ 9.4841e-02]]],


        ...,


        [[[ 1.3034e-02]],

         [[ 1.6503e-02]],

         [[ 1.4372e-02]],

         ...,

         [[-2.5991e-02]],

         [[ 5.5633e-02]],

         [[-7.9979e-02]]],


        [[[ 6.8067e-02]],

         [[-8.3669e-02]],

         [[-7.0316e-02]],

         ...,

         [[-2.85

# Step 3: Test

In [12]:
test(epoch)


Test set: Average loss: 0.4542, Accuracy: 8932/10000 (89.32%)

